services:
  - type: web
    name: my-fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-supabase-db
          property: connectionString
databases:
  - name: my-supabase-db
    plan: free
